// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ocboogie/pixel-art/repositories (interfaces: Session)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/ocboogie/pixel-art/models"
	reflect "reflect"
)

// RepositorySession is a mock of Session interface
type RepositorySession struct {
	ctrl     *gomock.Controller
	recorder *RepositorySessionMockRecorder
}

// RepositorySessionMockRecorder is the mock recorder for RepositorySession
type RepositorySessionMockRecorder struct {
	mock *RepositorySession
}

// NewRepositorySession creates a new mock instance
func NewRepositorySession(ctrl *gomock.Controller) *RepositorySession {
	mock := &RepositorySession{ctrl: ctrl}
	mock.recorder = &RepositorySessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *RepositorySession) EXPECT() *RepositorySessionMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *RepositorySession) Create(arg0 *models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *RepositorySessionMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*RepositorySession)(nil).Create), arg0)
}

// Delete mocks base method
func (m *RepositorySession) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *RepositorySessionMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*RepositorySession)(nil).Delete), arg0)
}

// Find mocks base method
func (m *RepositorySession) Find(arg0 string) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *RepositorySessionMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*RepositorySession)(nil).Find), arg0)
}
