// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ocboogie/pixel-art/services/feed (interfaces: Service)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ocboogie/pixel-art/models"
	repositories "github.com/ocboogie/pixel-art/repositories"
)

// ServiceFeed is a mock of Service interface.
type ServiceFeed struct {
	ctrl     *gomock.Controller
	recorder *ServiceFeedMockRecorder
}

// ServiceFeedMockRecorder is the mock recorder for ServiceFeed.
type ServiceFeedMockRecorder struct {
	mock *ServiceFeed
}

// NewServiceFeed creates a new mock instance.
func NewServiceFeed(ctrl *gomock.Controller) *ServiceFeed {
	mock := &ServiceFeed{ctrl: ctrl}
	mock.recorder = &ServiceFeedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ServiceFeed) EXPECT() *ServiceFeedMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *ServiceFeed) Create(arg0 models.PostNew) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *ServiceFeedMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*ServiceFeed)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *ServiceFeed) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *ServiceFeedMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*ServiceFeed)(nil).Delete), arg0)
}

// Find mocks base method.
func (m *ServiceFeed) Find(arg0 string, arg1 repositories.PostIncludes) (*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *ServiceFeedMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*ServiceFeed)(nil).Find), arg0, arg1)
}

// Latest mocks base method.
func (m *ServiceFeed) Latest(arg0 int, arg1 *time.Time, arg2 repositories.PostIncludes) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Latest", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Latest indicates an expected call of Latest.
func (mr *ServiceFeedMockRecorder) Latest(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Latest", reflect.TypeOf((*ServiceFeed)(nil).Latest), arg0, arg1, arg2)
}

// Like mocks base method.
func (m *ServiceFeed) Like(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Like indicates an expected call of Like.
func (mr *ServiceFeedMockRecorder) Like(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*ServiceFeed)(nil).Like), arg0, arg1)
}

// PostsByUser mocks base method.
func (m *ServiceFeed) PostsByUser(arg0 string, arg1 int, arg2 *time.Time, arg3 repositories.PostIncludes) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostsByUser", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostsByUser indicates an expected call of PostsByUser.
func (mr *ServiceFeedMockRecorder) PostsByUser(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostsByUser", reflect.TypeOf((*ServiceFeed)(nil).PostsByUser), arg0, arg1, arg2, arg3)
}

// Unlike mocks base method.
func (m *ServiceFeed) Unlike(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlike", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlike indicates an expected call of Unlike.
func (mr *ServiceFeedMockRecorder) Unlike(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlike", reflect.TypeOf((*ServiceFeed)(nil).Unlike), arg0, arg1)
}
